### ISSUE TITLE
Bug due to undefined variables in rare cases

### ISSUE THREAD

**Issue by chrisAta** [nawrockie/cmsearch_tblout_deoverlap#3]
Hello!

I was using cmsearch-deoverlap.pl on some unique primer sequences to validate their matches onto Rfam, so my input is quite small, with some sequences targets only having one match. I'm also sorting by bitscore, because the amount of sequences making up the 'database' is quite small.

This has led to a very specific issue that throws the `ERROR found lines with same target [$target] incorrectly sorted by score, did you sort by sequence name and score?` error message, which happens when:

- The first target after sorting by bitscore only has one match
- The bitscore of the next match is higher than the bitscore of the previous match

This error is happening because the $prv_score variable is still undefined at this stage, which causes it to enter this condition causing the script to exit with an error: https://github.com/nawrockie/cmsearch_tblout_deoverlap/blob/8d7d2df4bbc17aecb7f8b779a3157cfed95e5368/cmsearch-deoverlap.pl#L443 

I was able to fix it locally by checking whether $prv_score (and $prv_evalue) are defined in these if statements like this:
```
      if($rank_by_score && defined($prv_score) && ($score > $prv_score)) {
        die "ERROR found lines with same target [$target] incorrectly sorted by score, did you sort by sequence name and score?";
      }
      elsif((! $rank_by_score) && defined($prv_evalue) && ($evalue < $prv_evalue)) {
        die "ERROR found lines with same target [$target] incorrectly sorted by E-value, did you sort by sequence name and E-value?";
      }
```

Would be great if this could be fixed, thank you!

Chris

**Comment by chrisAta** [comment]
cmsearch-deoverlap seems to work fine with the latest bioconda version (0.09), which I only noticed now. I will close this now, thank you!

**Comment by nawrockie** [comment]
Thanks @chrisAta . Apologies, I somehow didn't notice this issue before you just closed it. Glad it is fixed.
